### ISSUE TITLE
discretize Smith Island into 500 m segments

### ISSUE THREAD

**Issue by anardek** [UNC-CECL/CASCADE#17]
What you would need to do is break up Cedar Island (LiDAR) into 500-m segments and convert from m NAVD88 to MHW (I think the MHW at Hog was 0.46 m NAVD88). Once you have that done (save as csv), we can discuss other initial conditions that may vary for each segment (dunes).

**Comment by franklin1895** [comment]
Wreck island is split into 9 500m long sections. Data from DEMs in ARC have been converted into decameters and given a new MHW datum. Each 500 by 500 m section has been straightened in R. R script finds the dune location and records values landward of the dune

**Comment by anardek** [comment]
Awesome! Did you use the default MHW from Smith Island? (0.46 m NAVD88 -- if we change this, we will need a new storm time series).

**Comment by anardek** [comment]
Can you include a plot of the new domains here? Here is some example code to do that for an individual B3D domain within CASCADE.

`plt.imshow(
    cascade.barrier3d[0]._DomainTS[i_min_pt75] * 10,
    origin="lower",
    cmap="terrain",
    vmin=-1.1,
    vmax=4.0,
)
plt.colorbar()
`

**Comment by franklin1895** [comment]
Here are the island interiors from Wreck:
![CP1](https://user-images.githubusercontent.com/85505371/176242908-762e0b2d-2971-4435-a89b-e925ba442be4.png)
![CP2](https://user-images.githubusercontent.com/85505371/176242924-49c81298-2b10-4ab6-b91f-b93dde724639.png)
![CP3](https://user-images.githubusercontent.com/85505371/176242949-faaa395c-0dd9-4002-8417-bbce2b292ec6.png)
![CP4](https://user-images.githubusercontent.com/85505371/176242976-d3835008-b920-4dc2-b94b-bd7b073ed8cf.png)
![CP5](https://user-images.githubusercontent.com/85505371/176243002-60232b97-c49f-42ee-8170-1c0fe325fdd9.png)
![CP6](https://user-images.githubusercontent.com/85505371/176243023-899e0259-5e24-4e62-a8d3-f4dcc432ac84.png)
![CP7](https://user-images.githubusercontent.com/85505371/176243039-3da230a6-e309-4bef-a74d-2ec305bf96b3.png)
![CP8](https://user-images.githubusercontent.com/85505371/176243065-9a6a5c14-c8ba-4bd3-a9ec-736a1704d9b6.png)
![CP9](https://user-images.githubusercontent.com/85505371/176243081-d05a52b9-0e63-4dda-bceb-5311484830de.png)

**Comment by franklin1895** [comment]
It looks like 3 m is the set depth in the parameter yaml file for the bay, but I don't think it over writes existing depth values. Here's a Barrier 3d run I just completed using one of my parameter files.

![image](https://user-images.githubusercontent.com/85505371/176490927-bf5e9c8d-7100-4e85-8ee4-660e6ffbf6e8.png)

**Comment by franklin1895** [comment]
I'll figure out the offsets. I did not set all underwater elevations to be - 3m. I should be able to add a color bar without too much trouble. I'll take a look at making a load script, I have a good idea about how I would do it in R, so it shouldn't be that hard to make it Python.

**Comment by franklin1895** [comment]
![Alongshore offesets](https://user-images.githubusercontent.com/85505371/176721914-3c438727-c8b5-4259-a234-8e513f7b6c15.png)


I have calculated the offsets for the sections:
S1 (Section 1) = 234
S2 = 309
S3 = 329
S4 =  359
S5 = 360
S6 = 303
S7 = 253
S8 = 155
S9 = 0

**Comment by anardek** [comment]
We shouldn't be including marsh in the barrier interior domain (we cannot yet resolve marsh processes. The top plot looks good to me.

To add a color bar, try something like this:
` cax = axs[iCascade].matshow(
            AnimateDomain, origin="lower", cmap="terrain", vmin=-1.1, vmax=3.0
        )  # , interpolation='gaussian')`
`cbar = fig.colorbar(cax)`
 `cbar.set_label("elevation (m MHW)", rotation=270)`

**Comment by franklin1895** [comment]
Offsets are now working. Thanks for all your help yesterday:

[](url
![elev_0](https://user-images.githubusercontent.com/85505371/178602737-639be955-0d42-4712-9528-913ce6b46eab.png)
)

**Comment by anardek** [comment]
Nice work Benton! Have you pushed the code? I want to take a look.

**Comment by franklin1895** [comment]
I have pushed the code to my branch on Github. I also included new topographic files and a script I use for running and animating my plots
